name: Tag accepted i2b2 Docker Images with version (exact commit - eg ff merge)
## Update the docker image/package tags - image must be tagged with this commit's sha
## Adapted from: https://github.com/marketplace/actions/docker-registry-tag
## You must tag the commit where the package was built, so best to squash commit the branch (or a candidate branch of the branch) for the actual build, which can then be fast forward merged into master

on:
  push:
    tags:
      - v[0-9]+.[0-9]+**

env:
  REGISTRY: ghcr.io
  token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tag_check:
    runs-on: ubuntu-latest
    if: $(git branch -r -a --contains "${{ github.sha }}" | grep -v detached | tr -d "*" | tr -s " " | grep "master")))
    outputs:
      tag_package_status: ${{ steps.status.outputs.tag_packages }}
      package_names: ${{ steps.status.outputs.package_names }}
    steps:
      - name: Pre-requisites
        id: status
        if: ${{ !startsWith(github.event.head_commit.message, 'Merge pull request') }}
        run: |
          echo ::set-output name=tag_packages::'true'
          echo "Tagging of packages should happen as we are receiving a tag on master branch..."

  tag_packages:
    runs-on: ubuntu-latest
    needs: [tag_check]
    if: needs.tag_check.outputs.tag_package_status == 'true'
    steps:
      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add git Version tag to proxy Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ env.REGISTRY }}'
          token: "${{ env.token }}"
          repository: '${{ github.repository }}/${{ github.event.repository.name }}-proxy'
          ## NOTE: Alternate package tag/reference while we don't want this full build code committed to master
          # target: 'sha-${{ github.sha }}'
          target: 'build-latest'
          tags: |
            v${{ steps.prep.outputs.version }}
            latest
      - name: Add git Version tag to web Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ env.REGISTRY }}'
          token: "${{ env.token }}"
          repository: '${{ github.repository }}/${{ github.event.repository.name }}-web'
          ## NOTE: Alternate package tag/reference while we don't want this full build code committed to master
          # target: 'sha-${{ github.sha }}'
          target: 'build-latest'
          tags: |
            v${{ steps.prep.outputs.version }}
            latest
      - name: Add git Version tag to wildfly Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ env.REGISTRY }}'
          token: "${{ env.token }}"
          repository: '${{ github.repository }}/${{ github.event.repository.name }}-wildfly'
          ## NOTE: Alternate package tag/reference while we don't want this full build code committed to master
          # target: 'sha-${{ github.sha }}'
          target: 'build-latest'
          tags: |
            v${{ steps.prep.outputs.version }}
            latest
      - name: Add git Version tag to database Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ env.REGISTRY }}'
          token: "${{ env.token }}"
          repository: '${{ github.repository }}/${{ github.event.repository.name }}-database'
          ## NOTE: Alternate package tag/reference while we don't want this full build code committed to master
          # target: 'sha-${{ github.sha }}'
          target: 'build-latest'
          tags: |
            v${{ steps.prep.outputs.version }}
            latest
      - name: Add git Version tag to api Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ env.REGISTRY }}'
          token: "${{ env.token }}"
          repository: '${{ github.repository }}/${{ github.event.repository.name }}-api'
          ## NOTE: Alternate package tag/reference while we don't want this full build code committed to master
          # target: 'sha-${{ github.sha }}'
          target: 'build-latest'
          tags: |
            v${{ steps.prep.outputs.version }}
            latest
      # - name: Add git Version tag to meta Docker Image
      #   uses: shrink/actions-docker-registry-tag@v1
      #   with:
      #     registry: '${{ env.REGISTRY }}'
      #     token: "${{ env.token }}"
      #     repository: '${{ github.repository }}/${{ github.event.repository.name }}-meta'
      #     ## NOTE: Alternate package tag/reference while we don't want this full build code committed to master
      #     # target: 'sha-${{ github.sha }}'
      #     target: 'build-latest'
      #     tags: |
      #       v${{ steps.prep.outputs.version }}
      #       latest
